# 1. Data Inputs & Basic Checks

In [497]:
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
print("Setup Complete")

Setup Complete

In [498]:
beneficiary = pd.read_csv("/kaggle/input/datasets/sophiali/datahealthcare/Train_Beneficiarydata-1542865627584.csv/Train_Beneficiarydata-1542865627584.csv")
inpatient = pd.read_csv("/kaggle/input/datasets/sophiali/datahealthcare/Train_Inpatientdata-1542865627584.csv/Train_Inpatientdata-1542865627584.csv")
outpatient = pd.read_csv("/kaggle/input/datasets/sophiali/datahealthcare/Train_Outpatientdata-1542865627584.csv/Train_Outpatientdata-1542865627584.csv")
train = pd.read_csv("/kaggle/input/datasets/sophiali/datahealthcare/Train-1542865627584.csv")

In [499]:
print("{db_name} dataset has {r} rows and {c} columns".format(db_name = "beneficiary", r = beneficiary.shape[0], c = beneficiary.shape[1]))
print("{db_name} dataset has {r} rows and {c} columns".format(db_name = "inpatient", r = inpatient.shape[0], c = inpatient.shape[1]))
print("{db_name} dataset has {r} rows and {c} columns".format(db_name = "outpatient", r = outpatient.shape[0], c = outpatient.shape[1]))
print("{db_name} dataset has {r} rows and {c} columns".format(db_name = "train", r = train.shape[0], c = train.shape[1]))

beneficiary dataset has 138556 rows and 25 columns
inpatient dataset has 40474 rows and 30 columns
outpatient dataset has 517737 rows and 27 columns
train dataset has 5410 rows and 2 columns

### Take a look at the raw data table format

In [500]:
beneficiary.head(3)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaN,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaN,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40

In [501]:
inpatient.head(3)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [502]:
outpatient.head(3)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [503]:
train.head(3)

   Provider PotentialFraud
0  PRV51001             No
1  PRV51003            Yes
2  PRV51004             No

### Check The Primary Key Of the 4 Raw Data Tables
Check result:
1. The primary keys are unique in the 4 tables. no duplicated values
2. There is no overlapping of claim ID between inpatient claim IDs and outpatient claim IDs
3. Every claim BeneID (in inpatient and outpatient) exists in Beneficiary

In [504]:
# check if the primary keys in each table are unique
print("How many duplicated values for primary key BeneID in beneficiary table? {} row(s)".format(beneficiary.BeneID.duplicated().sum()))
print("How many duplicated values for primary key ClaimID in inpatient table? {} row(s)".format(inpatient.ClaimID.duplicated().sum()))
print("How many duplicated values for primary key ClaimID in outpatient table? {} row(s)".format(outpatient.ClaimID.duplicated().sum()))
print("How many duplicated values for primary key Provider in train table? {} row(s)".format(train.Provider.duplicated().sum()))

How many duplicated values for primary key BeneID in beneficiary table? 0 row(s)
How many duplicated values for primary key ClaimID in inpatient table? 0 row(s)
How many duplicated values for primary key ClaimID in outpatient table? 0 row(s)
How many duplicated values for primary key Provider in train table? 0 row(s)

In [505]:
# check if any overlapped claim IDs in inpatient and outpatient tables
pd.concat([inpatient.ClaimID, outpatient.ClaimID]).duplicated().sum()

np.int64(0)

In [506]:
# compute the number of distinct values in the union of inpatient and outpatient bene IDs
pd.concat([inpatient.BeneID, outpatient.BeneID]).nunique()

138556

In [507]:
# compute the resulting number of distinct values after the union of inpatient and outpatient bene IDs inner join with Bene ID table
pd.concat([inpatient.BeneID, outpatient.BeneID]).isin(beneficiary.BeneID).all()

np.True_

### Check The Join Key: Provider
Check result: 
1. the providers from inpatient and outpatient files are fully matched with the providers in train file.
2. total 5410 providers. 506 are flagged as potential fraud, 4904 are not

In [508]:
inpatient_providers = inpatient.groupby('Provider').ClaimID.nunique().reset_index().rename(columns={'ClaimID':'ClaimCount'})
outpatient_providers = outpatient.groupby('Provider').ClaimID.nunique().reset_index().rename(columns={'ClaimID':'ClaimCount'})
total_providers = inpatient_providers.merge(outpatient_providers, on = 'Provider', how = 'outer', suffixes = ('Inpatient', 'Outpatient'))

In [509]:
total_providers.head(1)

   Provider  ClaimCountInpatient  ClaimCountOutpatient
0  PRV51001                  5.0                  20.0

In [510]:
total_providers.shape

(5410, 3)

In [511]:
train.shape

(5410, 2)

In [512]:
train.head(1)

   Provider PotentialFraud
0  PRV51001             No

In [513]:
total_providers_w_fraud = total_providers.merge(train, on = 'Provider', how = 'outer')
total_providers_w_fraud.shape

(5410, 4)

In [514]:
print("out of total {0} providers, {1} are flagged as potential fraud, {2} are not"
      .format(total_providers_w_fraud.shape[0]
              , total_providers_w_fraud.groupby('PotentialFraud').Provider.count().Yes
              , total_providers_w_fraud.groupby('PotentialFraud').Provider.count().No))

out of total 5410 providers, 506 are flagged as potential fraud, 4904 are not

### Check beneficiary table
1. check all columns for NA, it's expected for DOD column which stands for date of death.

In [515]:
# check NA for columns
beneficiary.isnull().mean()

BeneID                             0.000000
DOB                                0.000000
DOD                                0.989744
Gender                             0.000000
Race                               0.000000
RenalDiseaseIndicator              0.000000
State                              0.000000
County                             0.000000
NoOfMonths_PartACov                0.000000
NoOfMonths_PartBCov                0.000000
ChronicCond_Alzheimer              0.000000
ChronicCond_Heartfailure           0.000000
ChronicCond_KidneyDisease          0.000000
ChronicCond_Cancer                 0.000000
ChronicCond_ObstrPulmonary         0.000000
ChronicCond_Depression             0.000000
ChronicCond_Diabetes               0.000000
ChronicCond_IschemicHeart          0.000000
ChronicCond_Osteoporasis           0.000000
ChronicCond_rheumatoidarthritis    0.000000
ChronicCond_stroke                 0.000000
IPAnnualReimbursementAmt           0.000000
IPAnnualDeductibleAmt              0.000000
OPAnnualReimbursementAmt           0.000000
OPAnnualDeductibleAmt              0.000000
dtype: float64

In [516]:
beneficiary.Gender.value_counts()

Gender
2    79106
1    59450
Name: count, dtype: int64

In [517]:
beneficiary.RenalDiseaseIndicator.value_counts()

RenalDiseaseIndicator
0    118978
Y     19578
Name: count, dtype: int64

# Data Issue: Chronic Conditions are encoded as 1 & 2 without official mapping 
Inferred 1 = Yes, 2 = No for all ChronicCond columns (assumed one coding scheme across the table):

1. Prevalence: for rare conditions, code 1 is the clear minority (cancer 12%, stroke 8%), which supports 1 = Yes. For common conditions (diabetes 60%, ischemic heart disease 68%, heart failure 49%) prevalence can’t distinguish the two readings.
2. Cost: code 1 has a higher P80 annual inpatient reimbursement for all 11 conditions (median is 0 for both groups because most beneficiaries have no inpatient stay).
3. Consistency: 79% of ESRD patients are coded 1 for kidney disease vs 21% of non-ESRD patients.

In [518]:
# Chronic Condition are saved as coded 1 = Yes, 2 = No — verify, then recode to 1/0
for col in beneficiary.columns[beneficiary.columns.str.startswith('ChronicCond')]:
    print(col, beneficiary.loc[:,col].value_counts(normalize=True).round(2).to_dict())

ChronicCond_Alzheimer {2: 0.67, 1: 0.33}
ChronicCond_Heartfailure {2: 0.51, 1: 0.49}
ChronicCond_KidneyDisease {2: 0.69, 1: 0.31}
ChronicCond_Cancer {2: 0.88, 1: 0.12}
ChronicCond_ObstrPulmonary {2: 0.76, 1: 0.24}
ChronicCond_Depression {2: 0.64, 1: 0.36}
ChronicCond_Diabetes {1: 0.6, 2: 0.4}
ChronicCond_IschemicHeart {1: 0.68, 2: 0.32}
ChronicCond_Osteoporasis {2: 0.73, 1: 0.27}
ChronicCond_rheumatoidarthritis {2: 0.74, 1: 0.26}
ChronicCond_stroke {2: 0.92, 1: 0.08}

Check for Chronic Conditions, there is no mapping for 1 & 2. check 1 is yes or no

In [519]:
for col in beneficiary.columns[beneficiary.columns.str.startswith('ChronicCond')]:
    print(col, beneficiary.groupby(col).IPAnnualReimbursementAmt.quantile(0.8).to_dict())

ChronicCond_Alzheimer {1: 9000.0, 2: 2200.0}
ChronicCond_Heartfailure {1: 9000.0, 2: 0.0}
ChronicCond_KidneyDisease {1: 12500.0, 2: 0.0}
ChronicCond_Cancer {1: 10020.0, 2: 4000.0}
ChronicCond_ObstrPulmonary {1: 12040.0, 2: 0.0}
ChronicCond_Depression {1: 8000.0, 2: 3000.0}
ChronicCond_Diabetes {1: 8000.0, 2: 0.0}
ChronicCond_IschemicHeart {1: 7294.000000000087, 2: 0.0}
ChronicCond_Osteoporasis {1: 7100.0, 2: 4000.0}
ChronicCond_rheumatoidarthritis {1: 9000.0, 2: 4000.0}
ChronicCond_stroke {1: 13100.0, 2: 4000.0}

In [520]:
beneficiary['RenalDiseaseIndicator'] = beneficiary.RenalDiseaseIndicator.replace({'0':'0', 'Y':'1'}).astype(int)

In [521]:
# Consistency check: ESRD patients should mostly also have kidney disease
pd.crosstab(beneficiary['RenalDiseaseIndicator'], beneficiary['ChronicCond_KidneyDisease'],
            normalize='index').round(2)

ChronicCond_KidneyDisease     1     2
RenalDiseaseIndicator
0                          0.23  0.77
1                          0.79  0.21

In [522]:
for col in beneficiary.columns[beneficiary.columns.str.startswith('ChronicCond')]:
    beneficiary[col] = beneficiary[col].replace({2: 0})

replaced all 2 to 0, so that 0 means no, 1 means yes

In [523]:
for col in beneficiary.columns[beneficiary.columns.str.startswith('ChronicCond')]:
    print(col, beneficiary.groupby(col).IPAnnualReimbursementAmt.quantile(0.8).to_dict())

ChronicCond_Alzheimer {0: 2200.0, 1: 9000.0}
ChronicCond_Heartfailure {0: 0.0, 1: 9000.0}
ChronicCond_KidneyDisease {0: 0.0, 1: 12500.0}
ChronicCond_Cancer {0: 4000.0, 1: 10020.0}
ChronicCond_ObstrPulmonary {0: 0.0, 1: 12040.0}
ChronicCond_Depression {0: 3000.0, 1: 8000.0}
ChronicCond_Diabetes {0: 0.0, 1: 8000.0}
ChronicCond_IschemicHeart {0: 0.0, 1: 7294.000000000087}
ChronicCond_Osteoporasis {0: 4000.0, 1: 7100.0}
ChronicCond_rheumatoidarthritis {0: 4000.0, 1: 9000.0}
ChronicCond_stroke {0: 4000.0, 1: 13100.0}

### Check Inpatient table

In [524]:
# check NA for columns
inpatient.isnull().mean()

BeneID                    0.000000
ClaimID                   0.000000
ClaimStartDt              0.000000
ClaimEndDt                0.000000
Provider                  0.000000
InscClaimAmtReimbursed    0.000000
AttendingPhysician        0.002767
OperatingPhysician        0.411227
OtherPhysician            0.884123
AdmissionDt               0.000000
ClmAdmitDiagnosisCode     0.000000
DeductibleAmtPaid         0.022212
DischargeDt               0.000000
DiagnosisGroupCode        0.000000
ClmDiagnosisCode_1        0.000000
ClmDiagnosisCode_2        0.005584
ClmDiagnosisCode_3        0.016702
ClmDiagnosisCode_4        0.037901
ClmDiagnosisCode_5        0.071503
ClmDiagnosisCode_6        0.119534
ClmDiagnosisCode_7        0.179325
ClmDiagnosisCode_8        0.245639
ClmDiagnosisCode_9        0.333473
ClmDiagnosisCode_10       0.902975
ClmProcedureCode_1        0.428077
ClmProcedureCode_2        0.865247
ClmProcedureCode_3        0.976158
ClmProcedureCode_4        0.997134
ClmProcedureCode_5        0.999778
ClmProcedureCode_6        1.000000
dtype: float64

### Check Outpatient table

In [525]:
# check NA for columns
outpatient.isnull().mean()

BeneID                    0.000000
ClaimID                   0.000000
ClaimStartDt              0.000000
ClaimEndDt                0.000000
Provider                  0.000000
InscClaimAmtReimbursed    0.000000
AttendingPhysician        0.002696
OperatingPhysician        0.824975
OtherPhysician            0.623272
ClmDiagnosisCode_1        0.020190
ClmDiagnosisCode_2        0.377373
ClmDiagnosisCode_3        0.607413
ClmDiagnosisCode_4        0.757414
ClmDiagnosisCode_5        0.856406
ClmDiagnosisCode_6        0.905829
ClmDiagnosisCode_7        0.936336
ClmDiagnosisCode_8        0.955746
ClmDiagnosisCode_9        0.971341
ClmDiagnosisCode_10       0.997908
ClmProcedureCode_1        0.999687
ClmProcedureCode_2        0.999930
ClmProcedureCode_3        0.999992
ClmProcedureCode_4        0.999996
ClmProcedureCode_5        1.000000
ClmProcedureCode_6        1.000000
DeductibleAmtPaid         0.000000
ClmAdmitDiagnosisCode     0.796373
dtype: float64

# 2. Data Cleaning & Derived Column Preparation

### Convert Date Columns to DateTime Data Type, Add duration related derived columns

In [526]:
for col in beneficiary[['DOB','DOD']]:
    beneficiary[col] = pd.to_datetime(beneficiary[col])
    print(col, beneficiary[col].dtypes)

DOB datetime64[ns]
DOD datetime64[ns]

In [527]:
data_date = max(pd.to_datetime(inpatient.ClaimEndDt).max(), pd.to_datetime(outpatient.ClaimEndDt).max())
print(data_date)

2009-12-31 00:00:00

### Beneficiary table to add column age, num of chronical conditions

In [528]:
# compute age from either date of death or the data date depending on if DOD is available
beneficiary['Age'] = beneficiary.apply(lambda row: (data_date - row['DOB']).days //365.25 if pd.isnull(row['DOD']) else (row['DOD'] - row['DOB']).days // 365.25, axis=1)

In [529]:
for row in range (0,10):
    print("the patient is {0} years old, and was born on {1}, the date of death is {2}".format(beneficiary.iloc[row].Age, beneficiary.iloc[row].DOB,beneficiary.iloc[row].DOD))

the patient is 66.0 years old, and was born on 1943-01-01 00:00:00, the date of death is NaT
the patient is 73.0 years old, and was born on 1936-09-01 00:00:00, the date of death is NaT
the patient is 73.0 years old, and was born on 1936-08-01 00:00:00, the date of death is NaT
the patient is 87.0 years old, and was born on 1922-07-01 00:00:00, the date of death is NaT
the patient is 74.0 years old, and was born on 1935-09-01 00:00:00, the date of death is NaT
the patient is 33.0 years old, and was born on 1976-09-01 00:00:00, the date of death is NaT
the patient is 69.0 years old, and was born on 1940-09-01 00:00:00, the date of death is 2009-12-01 00:00:00
the patient is 75.0 years old, and was born on 1934-02-01 00:00:00, the date of death is NaT
the patient is 80.0 years old, and was born on 1929-06-01 00:00:00, the date of death is NaT
the patient is 73.0 years old, and was born on 1936-07-01 00:00:00, the date of death is NaT

In [530]:
chronic_cols = beneficiary.columns[beneficiary.columns.str.startswith('ChronicCond_')]
chronic_cols

Index(['ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke'],
      dtype='object')

In [531]:
beneficiary['n_chronicCond'] = beneficiary[chronic_cols].sum(axis=1)
beneficiary['n_chronicCond'].head(3)

0    7
1    0
2    2
Name: n_chronicCond, dtype: int64

In [532]:
all_chronic_cols = beneficiary.columns[beneficiary.columns.str.startswith('ChronicCond_') | beneficiary.columns.str.endswith('_chronicCond')]
all_chronic_cols

Index(['ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'n_chronicCond'],
      dtype='object')

In [533]:
beneficiary[all_chronic_cols].head(3)

,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,n_chronicCond
0,1,0,1,0,0,1,1,1,0,1,1,7
1,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,0,2

In [534]:
for col in inpatient.columns:
    if col.endswith('Dt'):
        inpatient[col] = pd.to_datetime(inpatient[col])
        print(col, inpatient[col].dtypes)

ClaimStartDt datetime64[ns]
ClaimEndDt datetime64[ns]
AdmissionDt datetime64[ns]
DischargeDt datetime64[ns]

### Inpatient table to add length of stay, claim duration

In [535]:
inpatient['LengthOfStay'] = (inpatient.DischargeDt - inpatient.AdmissionDt).dt.days
inpatient['ClaimDurationDays'] = (inpatient.ClaimEndDt - inpatient.ClaimStartDt).dt.days

In [536]:
for row in range (0,3):
    print("this claim has {0} days of hospitalization, from {1} to {2}".format(inpatient.iloc[row].LengthOfStay, inpatient.iloc[row].AdmissionDt,inpatient.iloc[row].DischargeDt))
    print("this claim has {0} days for processing, from {1} to {2}".format(inpatient.iloc[row].ClaimDurationDays, inpatient.iloc[row].ClaimStartDt,inpatient.iloc[row].ClaimEndDt))

this claim has 6 days of hospitalization, from 2009-04-12 00:00:00 to 2009-04-18 00:00:00
this claim has 6 days for processing, from 2009-04-12 00:00:00 to 2009-04-18 00:00:00
this claim has 2 days of hospitalization, from 2009-08-31 00:00:00 to 2009-09-02 00:00:00
this claim has 2 days for processing, from 2009-08-31 00:00:00 to 2009-09-02 00:00:00
this claim has 3 days of hospitalization, from 2009-09-17 00:00:00 to 2009-09-20 00:00:00
this claim has 3 days for processing, from 2009-09-17 00:00:00 to 2009-09-20 00:00:00

In [537]:
for col in outpatient.columns:
    if col.endswith('Dt'):
        outpatient[col] = pd.to_datetime(outpatient[col])

# Some claims have length of stay unmatched with claim duration days
1. Claim end date is later than discharge date -> 17 claims, suspicious
2. admission date is earlier than claim start date -> 32 claims, acceptable, may be due to claim split

In [538]:
n_claim_with_claim_period_diff = claims[(claims.ClaimType == 'IP') & (claims.LengthOfStay != claims.ClaimDurationDays)].shape[0]
print("no. of claims with claim period different from length of stay is", n_claim_with_claim_period_longer)

no. of claims with claim period different from length of stay is 49

In [539]:
claims_w_diff_durations = claims[(claims.ClaimType == 'IP') & (claims.LengthOfStay != claims.ClaimDurationDays)][['ClaimID','AdmissionDt','DischargeDt','ClaimStartDt','ClaimEndDt']]
print("AdmissionDt < ClaimStartDt:",claims_w_diff_durations[claims_w_diff_durations.AdmissionDt < claims_w_diff_durations.ClaimStartDt].shape[0])
print("AdmissionDt > ClaimStartDt:",claims_w_diff_durations[claims_w_diff_durations.AdmissionDt > claims_w_diff_durations.ClaimStartDt].shape[0])
print("DischargeDt < ClaimEndDt:", claims_w_diff_durations[claims_w_diff_durations.DischargeDt < claims_w_diff_durations.ClaimEndDt].shape[0])
print("DischargeDt > ClaimEndDt:", claims_w_diff_durations[claims_w_diff_durations.DischargeDt > claims_w_diff_durations.ClaimEndDt].shape[0])

AdmissionDt < ClaimStartDt: 32
AdmissionDt > ClaimStartDt: 0
DischargeDt < ClaimEndDt: 17
DischargeDt > ClaimEndDt: 0

### Outpatient table to add claim duration

In [540]:
outpatient['ClaimDurationDays'] = (outpatient.ClaimEndDt - outpatient.ClaimStartDt).dt.days
for row in range (0,3):
    print("this claim has {0} days covered by the claim from {1} to {2}".format(outpatient.iloc[row].ClaimDurationDays, outpatient.iloc[row].ClaimStartDt,outpatient.iloc[row].ClaimEndDt))

this claim has 0 days covered by the claim from 2009-10-11 00:00:00 to 2009-10-11 00:00:00
this claim has 0 days covered by the claim from 2009-02-12 00:00:00 to 2009-02-12 00:00:00
this claim has 0 days covered by the claim from 2009-06-27 00:00:00 to 2009-06-27 00:00:00

In [541]:
# outpatient['LengthOfStay'] = 0
# removed because same day discharge also has length of stay = 0, removed to be clear

# 3. Data Integration (Combine inpatient & outpatient to claim)

In [542]:
inpatient.columns.size, outpatient.columns.size

(32, 28)

In [543]:
[c for c in inpatient.columns if c not in outpatient.columns]

['AdmissionDt', 'DischargeDt', 'DiagnosisGroupCode', 'LengthOfStay']

### Add an additional column to show the data source

In [544]:
inpatient['ClaimType'] = 'IP' # inpatient
outpatient['ClaimType'] = 'OP' # outpatient

### The two tables inpatient and outpatient union into claim table. the row count matches before and after the union

In [545]:
claims = pd.concat((inpatient,outpatient),ignore_index=True)
claims[claims['ClaimType']=='IP'].shape[0], claims[claims['ClaimType']=='OP'].shape[0], claims.shape[0]

(40474, 517737, 558211)

In [546]:
inpatient.shape[0], outpatient.shape[0], inpatient.shape[0] + outpatient.shape[0]

(40474, 517737, 558211)

In [547]:
inpatient[~inpatient.ClaimID.isin(claims.ClaimID)]

Empty DataFrame
Columns: [BeneID, ClaimID, ClaimStartDt, ClaimEndDt, Provider, InscClaimAmtReimbursed, AttendingPhysician, OperatingPhysician, OtherPhysician, AdmissionDt, ClmAdmitDiagnosisCode, DeductibleAmtPaid, DischargeDt, DiagnosisGroupCode, ClmDiagnosisCode_1, ClmDiagnosisCode_2, ClmDiagnosisCode_3, ClmDiagnosisCode_4, ClmDiagnosisCode_5, ClmDiagnosisCode_6, ClmDiagnosisCode_7, ClmDiagnosisCode_8, ClmDiagnosisCode_9, ClmDiagnosisCode_10, ClmProcedureCode_1, ClmProcedureCode_2, ClmProcedureCode_3, ClmProcedureCode_4, ClmProcedureCode_5, ClmProcedureCode_6, LengthOfStay, ClaimDurationDays, ClaimType]
Index: []

[0 rows x 33 columns]

### Add the potential fraud tag from train table

In [548]:
claims = claims.merge(train, on = 'Provider', how = 'left')

In [549]:
print("the claim table has {} rows and {} columns".format(claims.shape[0], claims.shape[1]))
print("number of claims that do not have a potential fraud tag is {}".format(claims.PotentialFraud.isnull().sum()))
claims.head(3)

the claim table has 558211 rows and 34 columns
number of claims that do not have a potential fraud tag is 0

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,LengthOfStay,ClaimDurationDays,ClaimType,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6,IP,Yes
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,7092.0,NaN,NaN,NaN,NaN,NaN,2.0,2,IP,No
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3,IP,No

### Claims with claim end date later than discharge date are all under providers that are flagged as potential fraud

In [550]:
claims[claims.ClaimEndDt > claims.DischargeDt].PotentialFraud.value_counts()

PotentialFraud
Yes    17
Name: count, dtype: int64

### Add n_diagnoses, n_procedures and n_physicians

In [551]:
claims.columns

Index(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
       'OtherPhysician', 'AdmissionDt', 'ClmAdmitDiagnosisCode',
       'DeductibleAmtPaid', 'DischargeDt', 'DiagnosisGroupCode',
       'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
       'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
       'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
       'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
       'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
       'ClmProcedureCode_6', 'LengthOfStay', 'ClaimDurationDays', 'ClaimType',
       'PotentialFraud'],
      dtype='object')

In [552]:
diagnoses_cols = [c for c in claims.columns if 'Diagnosis' in c and c != 'ClmAdmitDiagnosisCode' and c != 'DiagnosisGroupCode']
procedures_cols = [c for c in claims.columns if 'Procedure' in c]
physicians_cols = [c for c in claims.columns if 'Physician' in c]

print("diagnoses_cols:", diagnoses_cols)
print("procedures_cols:", procedures_cols)
print("physicians_cols:", physicians_cols)

diagnoses_cols: ['ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10']
procedures_cols: ['ClmProcedureCode_1', 'ClmProcedureCode_2', 'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5', 'ClmProcedureCode_6']
physicians_cols: ['AttendingPhysician', 'OperatingPhysician', 'OtherPhysician']

In [553]:
claims['n_diagnoses'] = pd.notnull(claims[diagnoses_cols]).sum(axis = 1)
claims[[c for c in claims.columns if 'Diagno'.lower() in c.lower()]].head(3)

,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,n_diagnoses
0,7866,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,9
1,6186,750,6186,2948,56400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
2,29590,883,29623,30390,71690,34590,V1581,32723,NaN,NaN,NaN,NaN,6

In [554]:
claims['n_procedures'] = pd.notnull(claims[procedures_cols]).sum(axis = 1)
claims[[c for c in claims.columns if 'procedure'.lower() in c.lower()]].head(3)

,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,n_procedures
0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,7092.0,NaN,NaN,NaN,NaN,NaN,1
2,NaN,NaN,NaN,NaN,NaN,NaN,0

In [555]:
claims['n_physicians'] = pd.notnull(claims[physicians_cols]).sum(axis = 1)
claims[[c for c in claims.columns if 'physician'.lower() in c.lower()]].head(3)

  AttendingPhysician OperatingPhysician OtherPhysician  n_physicians
0          PHY390922                NaN            NaN             1
1          PHY318495          PHY318495            NaN             2
2          PHY372395                NaN      PHY324689             2

### Check InscClaimAmtReimbursed for zero and negative cases

In [556]:
print("no. of claims with claim amount = 0 is", claims[claims.InscClaimAmtReimbursed == 0].shape[0])
print("no. of claims with claim amount < 0 is", claims[claims.InscClaimAmtReimbursed < 0].shape[0])

no. of claims with claim amount = 0 is 20653
no. of claims with claim amount < 0 is 0

In [557]:
claims['is_zero_reimbursed'] = claims.InscClaimAmtReimbursed == 0

In [558]:
n_zero_claim_wo_deductible = claims[(claims.InscClaimAmtReimbursed == 0) & (claims.DeductibleAmtPaid <= 0)].shape[0]
print("no. of claim with claim amount = 0 and deductible <= 0 is", n_zero_claim_wo_deductible)

no. of claim with claim amount = 0 and deductible <= 0 is 18665

### Join beneficiary table to the claim table

In [559]:
beneficiary.shape, beneficiary.columns

((138556, 27),
 Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
        'State', 'County', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
        'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
        'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
        'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
        'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
        'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
        'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
        'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
        'OPAnnualDeductibleAmt', 'Age', 'n_chronicCond'],
       dtype='object'))

In [560]:
claims_w_bene = claims.merge(beneficiary, on = 'BeneID', how = 'left')

In [561]:
print("the claim with beneficiary table has {} rows and {} columns".format(claims_w_bene.shape[0], claims_w_bene.shape[1]))

the claim with beneficiary table has 558211 rows and 64 columns

# Compute the Potential Fraud %

In [562]:
claims_w_bene.head(1)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,Age,n_chronicCond
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,1,0,1,1,36000,3204,60,70,66.0,7

In [563]:
claim_fraud_per = claims_w_bene[claims_w_bene.PotentialFraud=='Yes'].ClaimID.nunique() / claims_w_bene.ClaimID.nunique()
provider_fraud_per = claims_w_bene[claims_w_bene.PotentialFraud=='Yes'].Provider.nunique() / claims_w_bene.Provider.nunique()

In [564]:
print("% of claims from providers flagged as potential fraud is", round(claim_fraud_per * 100, 2), "%")
print("% of providers that are flagged potential fraud is", round(provider_fraud_per * 100, 2), "%")

% of claims from providers flagged as potential fraud is 38.12 %
% of providers that are flagged potential fraud is 9.35 %

In [565]:
claims_w_bene.to_csv('claims_w_bene')